development: 
  cloud_name: "hrwa243my"
  api_key: "651168515613976"
  api_secret: "j4ppF_lP4_W4a6H5Ij7S5t3XpUc"
  secure: true

production:
  cloud_name: "hrwa243my"
  api_key: "651168515613976"
  api_secret: "j4ppF_lP4_W4a6H5Ij7S5t3XpUc"
  secure:true